### ISSUE TITLE
How to authenticate yourself when using websockets

### ISSUE THREAD

**Issue by tiany7** [Hsin-Hung/binance_api_cpp#2]
To Whom It May Concern:
Hello, I'm a newbie developer. I'm trying to use this repository to connect to binance, but I don't seem to see how to provide api_key and secret in websocket, and there doesn't seem to be any relevant prompts in the code. I would like to ask how to authenticate?
Sincerely
tiany7

**Comment by Hsin-Hung** [comment]
You don't need a key for these public data streams. However, you will need a VPN if your country blocks Binance.
